version: '3.8'

 
services:
  # Blazor App Service
  blazorapp:
    image: fitskedapp:v1
    ports:
      - "8085:8080"  # Host:Container port mapping for Blazor app
    networks:
      - mynetwork
    depends_on:
      - sqlserver  # Ensure SQL Server starts first
      - exerciseapi  # Ensure Exercise API starts before Blazor app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Environment for Blazor app
      - EXERCISE_API_BASE_URL=http://exerciseapi:5000  # Internal API URL for Blazor app

  # SQL Server Service
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server2022
    # ports 1443
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Sportlife#32#sqlserver#32#
    networks:
      - mynetwork
    volumes:
      - sql_data:/var/opt/mssql 

  # Exercise API Service
  exerciseapi:
    image: exercise-api:v1
    ports:
      - "5000:5279"  # Host:Container port mapping for Exercise API
    networks:
      - mynetwork
    depends_on:
      - sqlserver  # Ensure SQL Server starts first
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Environment for Exercise API
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=ExerciseDb;User Id=sa;Password=Sportlife#32#sqlserver#32#;

networks:
  mynetwork:
    driver: bridge

volumes:
  sql_data:
    driver: local
