version: '3.8'

services:
  blazorapp:
    image: fitskedapp:v1
    ports:
      - "8085:8080"
    networks:
      - mynetwork
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development   # Added to enable development environment
      
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Sportlife#32#sqlserver#32#
    container_name: sql_server2022
    networks:
      - mynetwork
    volumes:
      - sql_data:/var/opt/mssql

networks:
  mynetwork:
    driver: bridge

volumes:
  sql_data:
    driver: local
