name: Run tests for development environment

on:
  pull-request:
  # Sequence of patterns matched against refs/heads
    branches: ["develop"]

permissions:
  contents: read # This just tells us the permissions we have on reading GitHub contents. Nothing to do with why application is shutting down I don't think.

jobs:
  deploy:
    name: Deploy to development
    runs-on: ubuntu-latest # Github Actions runs on a linux machine regardless
    environment: development

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Linting
      uses: 
      #There is no need for a StyleCop CLI tool, it's plugged directly to MSBuild. We are using StyleCop + Resharper + EditorConfig, which catch most of the inconsistencies.



 

