name: Build & Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    # Checkout out is essentially just allowing the action to see the codebase that it will act upon 
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Login Dockerhub
        env:
          DOCKER_USERNAME=${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u DOCKER_USERNAME -p DOCKER_PASSWORD

      - name: Build the Docker Image
        run: docker build -t exercise-api-app .
      - name: Push to Docker Hub
        run: docker push thecodeiackiller/exercise-api-app:latest

      # By default, metadata-action uses metadata such as branch names like main as the tags for a repository listed below.
      # - name: Extract Docker image metadata
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: ${{ vars.DOCKER_USERNAME }}/exercise-api-app

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ vars.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v6
      #   with:
      #     push: ${{ github.event_name != 'pull_request' }}
      #     tags: ${{ steps.meta.outputs.tags }}
      #     annotations: ${{ steps.meta.outputs.annotations }}
      #     provenance: true
      #     sbom: true
