name: Deploy Image

on:
  workflow_run:
    workflows: ["Build & Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Pull the latest Docker image from Docker Hub
      - name: Pull Latest Docker Image
        run: sudo docker pull thecodeiackiller/exercise-api-app:latest

      # Get SHA Digest of the Latest Image
      - name: Get Image Digest
        id: get-digest
        run: |
          IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' thecodeiackiller/exercise-api-app:latest | cut -d '@' -f 2)
          echo "IMAGE_DIGEST=$IMAGE_DIGEST" >> $GITHUB_ENV

      # Remove old images
      - name: Remove Old Images
        run: |
          # Find and remove all images except the latest digest
          docker images --format '{{.ID}} {{.Repository}}@{{.Digest}}' | grep -v "$IMAGE_DIGEST" | awk '{print $1}' | xargs -r docker rmi -f

      # Stop and Remove Old ECS Containers
      - name: Stop and Remove Old Containers
        run: |
          docker ps -aq --filter "name=ecs-blazor_app_task-65-blazorappcontainer*" | xargs -r docker stop
          docker ps -aq --filter "name=ecs-blazor_app_task-65-blazorappcontainer*" | xargs -r docker rm
          docker ps -aq --filter "name=blazor_app_container" | xargs -r docker stop
          docker ps -aq --filter "name=blazor_app_container" | xargs -r docker rm

      # Run the updated container with the correct digest
      - name: Run Updated Docker Container
        run: |
          sudo docker run -d -p 8080:8080 \
            --name blazor_app_container \
            thecodeiackiller/exercise-api-app@$IMAGE_DIGEST



      # - name: Log Current Docker Status
      #   run: |
      #     sudo docker ps -a
      #     sudo docker images

      # - name: Pull Latest Docker Image
      #   run: sudo docker pull thecodeiackiller/exercise-api-app:main

      # - name: Stop and Remove Existing Container
      #   run: |
      #     docker ps -aq --filter "name=exercise-api-app-container" | xargs -r docker stop
      #     docker ps -aq --filter "name=exercise-api-app-container" | xargs -r docker rm

      # - name: Remove Old Images
      #   run: |
      #     docker images -q --filter "dangling=true" | xargs -r docker rmi

      # - name: Run Updated Container
      #   run: sudo docker run -d -p 8080:8080 --name exercise-api-app-container thecodeiackiller/exercise-api-app

      # - name: Verify Container is Running
      #   run: |
      #     if ! sudo docker ps | grep exercise-api-app-container; then
      #       echo "Deployment failed: Container not running" && exit 1;
      #     fi
      # Adding comment so that I can push from a change.
      # Checking to see if the correct image updates in docker hub on push.
